language: c
os: linux
dist: trusty
git:
  depth: false
before_install:
- openssl aes-256-cbc -K $encrypted_403e3d772bdb_key -iv $encrypted_403e3d772bdb_iv
  -in travis_key.enc -out travis_key -d
- wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
- sudo wget https://files.viva64.com/etc/viva64.list -O /etc/apt/sources.list.d/viva64.list
install:
- sudo pip install gcovr
- sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib
  && sudo apt-get install -qq
- sudo apt-get install -qq pvs-studio
- sudo apt-get install -qq doxygen
- gem install ceedling
- pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY
- |
  wget -q https://sourceforge.net/projects/astyle/files/astyle/astyle%203.1/astyle_3.1_linux.tar.gz/download -O astyle.tar.gz
  tar -xvf astyle.tar.gz
  cd astyle
  mkdir as-gcc-exe
  cd as-gcc-exe
  cmake  ../
  make
  sudo make install
  cd ../../
script:
- doxygen Doxyfile
cache:
  directories:
  - nRF5_SDK_15.3.0_59ac345
sudo: false
branches:
  only:
  - master
addons:
  apt:
    packages:
    - doxygen
  sonarcloud:
    organization: ruuvi
    token:
      secure: "**************************"
before_deploy:
- sed -i '/doxygen/d' .gitignore
deploy:
  provider: pages
  cleanup: false
  keep_history: false
  local_dir: doxygen/html
  deploy_key: travis_key
  edge: true
  on:
    branch: master
